
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alondriwis
 */
import static javax.swing.JOptionPane.*;

public class VentanaLibro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLibro
     */
    public VentanaLibro() {
        initComponents();
        m = (DefaultTableModel) tblLibro.getModel();
        buttonGroup1.add(rbtnburbuja);
        buttonGroup1.add(rbtshell);
        buttonGroup1.add(rbtquick);
        buttonGroup2.add(rbtnasc);
        buttonGroup2.add(rbtndesc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar6 = new javax.swing.JToolBar();
        jToolBar8 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibro = new javax.swing.JTable();
        jToolBar7 = new javax.swing.JToolBar();
        btnguardar = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        btncan = new javax.swing.JToolBar();
        jToolBar5 = new javax.swing.JToolBar();
        btncancelar = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        btnbuscar = new javax.swing.JButton();
        jToolBar9 = new javax.swing.JToolBar();
        jLabel6 = new javax.swing.JLabel();
        cbmIndex = new javax.swing.JComboBox<>();
        txtvalue = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnaagregar = new javax.swing.JButton();
        btnbinaria = new javax.swing.JButton();
        rbtnburbuja = new javax.swing.JRadioButton();
        rbtshell = new javax.swing.JRadioButton();
        rbtquick = new javax.swing.JRadioButton();
        rbtnasc = new javax.swing.JRadioButton();
        rbtndesc = new javax.swing.JRadioButton();

        jToolBar6.setRollover(true);

        jToolBar8.setRollover(true);
        jToolBar6.add(jToolBar8);

        jButton3.setText("Cancelar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setText("ISBN");

        jLabel2.setText("Titulo");

        jLabel3.setText("Autor");

        jLabel4.setText("Editorial");

        jLabel5.setText("Precio");

        txtAutor.setEnabled(false);

        txtTitulo.setEnabled(false);

        txtisbn.setEnabled(false);

        txtEditorial.setEnabled(false);

        tblLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo", "Autor", "Editorial", "Precio"
            }
        ));
        tblLibro.setCellSelectionEnabled(true);
        tblLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibro);

        jToolBar7.setRollover(true);
        jToolBar7.setEnabled(false);

        btnguardar.setIcon(new javax.swing.ImageIcon("E:\\guardar.png")); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setEnabled(false);
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar7.add(btnguardar);

        txtPrecio.setEnabled(false);

        btncan.setRollover(true);
        btncan.setEnabled(false);

        jToolBar5.setRollover(true);
        btncan.add(jToolBar5);

        btncancelar.setIcon(new javax.swing.ImageIcon("E:\\cancelar.png")); // NOI18N
        btncancelar.setEnabled(false);
        btncancelar.setFocusable(false);
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        btncan.add(btncancelar);

        jToolBar4.setRollover(true);

        btnbuscar.setIcon(new javax.swing.ImageIcon("E:\\buscar.png")); // NOI18N
        btnbuscar.setText("Buscar por");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar4.add(btnbuscar);

        jToolBar9.setRollover(true);
        jToolBar4.add(jToolBar9);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alo\\Pictures\\TL.png")); // NOI18N

        cbmIndex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criterio", "ISBN", "titulo", "Autor", "Editorial", "Precio" }));
        cbmIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmIndexActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnaagregar.setIcon(new javax.swing.ImageIcon("E:\\agregar.png")); // NOI18N
        btnaagregar.setText("Agregar");
        btnaagregar.setFocusable(false);
        btnaagregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaagregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnaagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaagregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnaagregar);

        btnbinaria.setIcon(new javax.swing.ImageIcon("C:\\Users\\alo\\Pictures\\bus binaria.png")); // NOI18N
        btnbinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinariaActionPerformed(evt);
            }
        });

        rbtnburbuja.setText("Burbuja");

        rbtshell.setText("Shell");

        rbtquick.setText("Quicksort");

        rbtnasc.setText("Asc");

        rbtndesc.setText("Des");
        rbtndesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtndescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(178, 178, 178)
                                        .addComponent(rbtnasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtndesc))
                                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbtquick, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(rbtshell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnburbuja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnbinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btncan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cbmIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnburbuja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtshell))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtquick)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnasc)
                            .addComponent(rbtndesc))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        //boton de buscar en general por todos los campos
        if (!(txtvalue.getText().equals(""))) {
            if (Metodo.bSec(L, txtvalue.getText(), tblLibro.getRowCount())) {
                showMessageDialog(null, "se ha encontrado su busqueda");
           } //else {
              // showMessageDialog(null, "No se encontro  su busqueda");
           //}
       }//if
       else {
            showMessageDialog(null, "vacio");}
//showMessageDialog(null,busquedaSec(L,cbmIndex.getSelectedIndex(),txtvalue.getText()));

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        //darle click al guardar
        L[++tope] = new Libro(txtisbn.getText(), txtTitulo.getText(), txtAutor.getText(), txtEditorial.getText(), (Float.parseFloat(txtPrecio.getText())));
        //BloquearCampos();
        //limpicarcampos();
        desBloquearCampos();
        Object O[] = new Object[5];
        O[0] = L[tope].getISBN();
        O[1] = L[tope].getTitulo();
        O[2] = L[tope].getAutor();
        O[3] = L[tope].getEd();
        O[4] = L[tope].getPrecio();
        m.addRow(O);
        BloquearCampos();
        limpicarcampos();
        btnaagregar.setEnabled(true);
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        ///boton ce cancelar
        limpicarcampos();
        BloquearCampos();
        btnaagregar.setEnabled(true);
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);
        btnbuscar.setEnabled(false);
        //new VentanaLibro().setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void cbmIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmIndexActionPerformed
        if (cbmIndex.getSelectedIndex() != 0) {
            txtvalue.setEditable(true);
        } else {
            txtvalue.setEditable(false);
        }
    }//GEN-LAST:event_cbmIndexActionPerformed

    private void btnaagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaagregarActionPerformed
        //AGREGAR
        //desbloquear las cajas de texto para poder hacer registros
        desBloquearCampos();
        limpicarcampos();
        desBloquearBotones();
        // BloquearCampos(); txtisbn.requestFocus();
        //crear renglones en la tabla
        //m.setRowCount(m.getRowCount() + 1);

    }//GEN-LAST:event_btnaagregarActionPerformed

    private void btnbinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinariaActionPerformed
        // Busqueda binaria
        
        
       Libro[] L1=new Libro[m.getRowCount()];
       //showMessageDialog(null, m.getRowCount());
       for(int i=0;i<m.getRowCount();i++){
           
           L1[i]=new Libro(m.getValueAt(i,0).toString(),m.getValueAt(i,1).toString(),m.getValueAt(i,2).toString(),m.getValueAt(i,3).toString(),Float.parseFloat(m.getValueAt(i,4).toString()));
       }
       
       if(L1.length>0)
            Metodo.ordBurbuja(L1);
        
       int pos = binariaRecur(L1,txtvalue.getText(), 0, L1.length - 1);
       if (pos != -1) {
            showMessageDialog(rootPane, "se encuentra en la posición " + pos++);}
       else { showMessageDialog(rootPane, "no se encuentra ");} 
       
    }//GEN-LAST:event_btnbinariaActionPerformed

    private void rbtndescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtndescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtndescActionPerformed

    private void tblLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibroMouseClicked
        // Dar clic en cada columna para ordenar los datos
            int f=tblLibro.getSelectedColumn();
        L=new Libro [m.getRowCount()];
        for(int i=0;i<m.getRowCount();i++){
       L[i] = new Libro (m.getValueAt(i, 0).toString(),m.getValueAt(i,1).toString(),m.getValueAt(i, 2).toString(),
                                 m.getValueAt(i, 3).toString(),Float.parseFloat(m.getValueAt(i, 4).toString()));}
        boolean a=rbtnasc.isSelected();
        if(rbtnburbuja.isSelected()){
        Metodo.ordBurbujaAlmno(L, a,tblLibro.getSelectedColumn());
        }
        if(rbtquick.isSelected()){
        Metodo.quicksortLibro(L,0,a,L.length-1,tblLibro.getSelectedColumn());
        }
        if(rbtshell.isSelected()){
        Metodo.shellasc(L, a,tblLibro.getSelectedColumn());
        }
       // if(rbradix.isSelected()){
       // Examen_Unid5.radixMateria(M, a,btnmateria.getSelectedColumn());
       // }
         for(int i=0;i<L.length;i++){
            switch(f){
                case 0:
                     m.setValueAt(L[i].getISBN(), i, f);
                    break;
                case 1:
                     m.setValueAt(L[i].getTitulo(), i, f);
                    break;
                    case 2:
                     m.setValueAt(L[i].getAutor(), i, f);
                    break;
                    case 3:
                     m.setValueAt(L[i].getEd(), i, f);
                    break;
                    case 4:
                     m.setValueAt(L[i].getPrecio(), i, f);
                    break;
            }
         }
    }//GEN-LAST:event_tblLibroMouseClicked
    public void desBloquearCampos() {

        txtisbn.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtAutor.setEnabled(true);
        txtEditorial.setEnabled(true);
        txtPrecio.setEnabled(true);

    }

    public void BloquearCampos() {

        txtisbn.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtAutor.setEnabled(false);
        txtEditorial.setEnabled(false);
        txtPrecio.setEnabled(false);

    }

    public void limpicarcampos() {
        txtisbn.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtEditorial.setText("");
        txtPrecio.setText("");
    }

    public void desBloquearBotones() {
        btnaagregar.setEnabled(false);
        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnbuscar.setEnabled(true);
    }

    public Libro busquedaSec(Libro L[], int index, String value) {
        for (int i = 0; i < tope; i++) {
            switch (index) {
                case 0:
                    if (L[i].getISBN().equals(value)) {
                        return L[i];
                    }
                    break;
                case 1:
                    if (L[i].getTitulo().equals(value)) {
                        return L[i];
                    }
                    break;
                case 2:
                    if (L[i].getAutor().equals(value)) {
                        return L[i];
                    }
                    break;
                case 3:
                    if (L[i].getEd().equals(value)) {
                        return L[i];
                    }
                    break;
                case 4:
                    if ((L[i].getPrecio() + "").equals(value)) {
                        return L[i];
                    }
                    break;
            }//switch
        }
        showMessageDialog(null,"NO SE ENCONTRO EL DATO");
        return null;
    }
     public static int binariaRecur(Libro[] L, String valor, int inf, int sup) {
        int mitad = (inf + sup) / 2;
        if ((inf >= sup) && (L[inf].getISBN() != valor)) {
            return -1;
        } else if (L[mitad].getISBN().equals(valor)) {
            return mitad;
        } else if (valor.compareToIgnoreCase(L[mitad].getISBN())>0) {
            return binariaRecur(L, valor, mitad + 1, sup);
        }
        return binariaRecur(L, valor, inf, mitad - 1);
    } //binaria recursiva

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLibro().setVisible(true);
            }
        });
    }
    private Libro L[]= new Libro[100];
    private int A[];
    private int tope = -1;
    private DefaultTableModel m;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaagregar;
    private javax.swing.JButton btnbinaria;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JToolBar btncan;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbmIndex;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar jToolBar8;
    private javax.swing.JToolBar jToolBar9;
    private javax.swing.JRadioButton rbtnasc;
    private javax.swing.JRadioButton rbtnburbuja;
    private javax.swing.JRadioButton rbtndesc;
    private javax.swing.JRadioButton rbtquick;
    private javax.swing.JRadioButton rbtshell;
    private javax.swing.JTable tblLibro;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtvalue;
    // End of variables declaration//GEN-END:variables
}
